name: Docker image
on:
  - push

env:
  VENV_DIR: /venv
  VENV_BIN: /venv/bin

  IMAGE_PATH: "foodxtech/foodx-devops-tools-pipeline:${{ github.sha }}"


jobs:
  build-docker-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          docker build \
            -t ${{ env.IMAGE_PATH }} \
            .
          docker push ${{ env.IMAGE_PATH }}
